name: Weekly Stats Update

on:
  schedule:
    # Runs every Tuesday at 2:00 AM CST (08:00 UTC)
    - cron: "0 8 * * TUE"
  workflow_dispatch: {}  # Allows manual runs

jobs:
  update-stats:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run stats update
        env:
          ESPN_S2: ${{ secrets.ESPN_S2 }}
          SWID: ${{ secrets.SWID }}
        run: |
          python update_data.py

      - name: Commit and push updated stats.json
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add data/stats.json
          git commit -m "Weekly stats update" || echo "No changes to commit"
          git push
